### PR TITLE
Update to fix Lists/Arrays of nullables not getting marked as nullable

### LINKED ISSUE #3284: How do I get arrays of nullable types to be represented with a nullable flag in "items" in swagger
### What are you wanting to achieve?

I have a project which has a model in particular that contains arrays of nullable doubles.
When I generate the swagger for the project (using release 7.2.0), the arrays are marked as nullable, but the array items are not.

I have been reading through the issues that were resolved as part of release 7.1.0, and as far as I can tell the issue I'm experiencing should have been resolved as part of that release.

I must be missing something, but not sure what.

### What code or approach do you have so far?

For example, this is a field in my project:
`public double?[] Field1 { get; set; }`
I would expect this to be represented like this in the swagger output:
```
"Field1": {
  "type": "array",
  "items": {
    "type": "number",
    "format": "double",
    "nullable": true  
  },
  "nullable": true
}
```
But instead it is represented like this:
```
"Field1": {
  "type": "array",
  "items": {
    "type": "number",
    "format": "double"
  },
  "nullable": true
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Scarecrow7250**
# Pull Request

## The issue or feature being addressed

This Pull Request should hopefully address an issue where Arrays/Lists of Nullable types where not getting correctly marked as Nullable in the generated swagger.

Resolves #3284

## Details on the issue fix or feature implementation

In GenerateSchema -> GenerateSchemaForType I added a check to see if the Array underlying type was nullable. If so, it would mark the corresponding section in the schema (in this case items) with nullable = true.

### CODE REVIEW

File: src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs [hunk 1]
```diff
@@ -183,6 +183,8 @@ private OpenApiSchema GenerateSchemaForType(Type modelType, SchemaRepository sch
         if (schema.Reference == null)
         {
             ApplyFilters(schema, modelType, schemaRepository);
+            if (Nullable.GetUnderlyingType(modelType) != null)
+                schema.Nullable = true;
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs:187]:
```suggestion
            if (Nullable.GetUnderlyingType(modelType) != null)
            {
                schema.Nullable = true;
            }
```

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs [hunk 2]
```diff
@@ -161,28 +161,30 @@ public void GenerateSchema_GeneratesReferencedDictionarySchema_IfDictionaryTypeI
         Assert.Equal(schema.AdditionalProperties.Reference.Id, referenceSchema.Reference.Id); // ref to self
     }
 
-    public static TheoryData<Type, JsonSchemaType, string> EnumerableTypeData => new()
+    public static TheoryData<Type, JsonSchemaType, string, bool> EnumerableTypeData => new()
```
Comment (martincostello) [inline test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs:164]: There should be some test cases where we expect `true` (e.g. for `int?[]`).

**Review by martincostello — COMMENTED** [review]
Just some minor comments.

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs (hunk 2 above)
Comment (Scarecrow7250) [reply test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs:164]: Yep, I'll pop in a couple more scenarios

Comment (Scarecrow7250) [reply test/Swashbuckle.AspNetCore.SwaggerGen.Test/SchemaGenerator/JsonSerializerSchemaGeneratorTests.cs:164]: I've added some more test cases.
All unit tests are passing

**Review by martincostello — APPROVED** [review]
Thanks!
