### PR TITLE
Fixed problem with finding nullable attribute in nested types because of roslyn optimizations

### LINKED ISSUE #2017: 6.0.5 subclass non-nullable strings shown as nullable
Hi,

Great that the nullable reference types support is coming along! I tested it and found an issue that was a bit confusing.
When SupportNonNullableReferenceTypes is enabled:

```
public class TopLevelClass{
    public string TopNonNullableString { get; set; } = null!;
    public string? TopNullableString {get; set; }


    public class SubClass{
        public string SubNonNullableString { get; set; } = null!;
        public string? SubNullableString {get; set; }
    }
}
```

For the `TopLevelClass` the properties' nullable context is shown correctly, but for `SubClass` both are shown as nullable.
Now if I move the `SubClass` to be on the top level, the nullable context is shown correctly.

I'm on version 6.0.5

### PR DESCRIPTION
**Pull request by Eneuman**
This change only affects the logic in finding compiler annotated null attributes when using the "SupportNonNullableReferenceTypes" option.

- [x] Adjusted code to handle roslyn compiler optimizations for nested types.
- [x] Fixed bug that cause a crash if annotation nullable attribute flag returned was byte[].
- [x] Added tests for compiler optimization senarios.
- [x] Added default values to test class to remove warnings.

More information about roslyn nullable metadata can be found here https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md

This PR should fix #2017 and probobly #1487

### CODE REVIEW

File: src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs [hunk 1]
```diff
@@ -39,7 +39,10 @@ public static bool IsNonNullableReferenceType(this MemberInfo memberInfo)
                 ? ((FieldInfo)memberInfo).FieldType
                 : ((PropertyInfo)memberInfo).PropertyType;
 
-            if (memberType.IsValueType) return false;
+            if (memberType.IsValueType)
+            {
+                return false;
+            }
```
Comment (domaindrivendev) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs:45]: Could you please revert this change as it's stylistic not functional - I prefer the previous style

Comment (Eneuman) [reply src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs]: Code change reverted
