### PR TITLE
Fixing breaking change when applying filters for WithOpenApi extension

### LINKED ISSUE #3084: [Bug]: Parameter description breaking change in v6.8.0
Given the following

```csharp
using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();
app.UseSwagger();

app.MapGet("/test", (string filter) => "ok")
   .WithOpenApi(o => o
        .WithParameterDescription("filter", "Description for filter querystring parameter")
    );

app.Run();

public static class Extensions
{
    public static OpenApiOperation WithParameterDescription(this OpenApiOperation openApiOperation, string parameterName, string description)
    {
        var openApiParameter = openApiOperation.Parameters.Single(p => p.Name.Equals(parameterName, StringComparison.OrdinalIgnoreCase));
        openApiParameter.Description = description;

        return openApiOperation;
    }
}
```

`Swashbuckle.AspNetCore v6.7.3` generates the parameter with a description

```json
{
    "parameters": [
        {
            "name": "filter",
            "in": "query",
            "description": "Description for filter querystring parameter",
            "required": true,
            "schema": {
                "type": "string"
            }
        }
    ]
}
```

`Swashbuckle.AspNetCore v6.8.0` omits the description

```json
{
    "parameters": [
        {
            "name": "filter",
            "in": "query",
-           "description": "Description for filter querystring parameter",
            "required": true,
            "schema": {
                "type": "string"
            }
        }
    ]
}
```

@jgarciadelanoceda I suspect this is due to changes introduced in #3059

### PR DESCRIPTION
**Pull request by jgarciadelanoceda**
Fixes #3084
Tested with IntegrationTest

### CODE REVIEW

File: test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs [hunk 1]
```diff
@@ -42,10 +42,18 @@ public static IEndpointRouteBuilder MapWithOpenApiEndpoints(this IEndpointRouteB
...
 
-            group.MapPost("/IFromFile", (IFormFile file) =>
+            group.MapPost("/IFromFile", (IFormFile file, string queryParameter) =>
             {
-                return file.FileName;
-            }).WithOpenApi();
+                return $"{file.FileName}{queryParameter}";
+            }).WithOpenApi(o =>
+            {
+                var parameter = o.Parameters.FirstOrDefault(p => p.Name.Equals("queryParameter", StringComparison.InvariantCulture));
```
Comment (martincostello) [inline test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs:50]:
```suggestion
                var parameter = o.Parameters.FirstOrDefault(p => p.Name.Equals("queryParameter", StringComparison.OrdinalIgnoreCase));
```

Could you also change this one too please?

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/17981d9626ce04cc48932aa7443f909653d5fcdd/test/WebSites/Basic/Controllers/FilesController.cs#L44

**Review by martincostello — APPROVED** [review]
