### PR TITLE
Fix nested types nullable context check

### LINKED ISSUE #3040: [Bug]: SupportNonNullableReferenceTypes does not support nonnullables in nested types after the 2nd level of nesting
### Describe the bug

When using `SupportNonNullableReferenceTypes` in combination with having `Nullable` enabled, non-nullable types that are part of **nested** DTOs 3+ levels down still have `nullable` in their definition. E.g.

```
public record Zoo1(Zoo1.Zoo2 Level1, string Level1StringProp)
{
    public record Zoo2(Zoo2.Zoo3 Level2, string Level2StringProp)
    {
        public record Zoo3(Zoo3.Zoo4 Level3, string Level3StringProp)
        {
            public record Zoo4(string Level4StringProp);
        }
    }
}
```

### Expected behavior

Should generate:
```
    Zoo1:
      type: object
      properties:
        level1:
          allOf:
            - $ref: '#/components/schemas/Zoo1_Zoo2'
        level1StringProp:
          type: string
      additionalProperties: false
    Zoo1_Zoo2:
      type: object
      properties:
        level2:
          allOf:
            - $ref: '#/components/schemas/Zoo1_Zoo2_Zoo3'
        level2StringProp:
          type: string
      additionalProperties: false
    Zoo1_Zoo2_Zoo3:
      type: object
      properties:
        level3:
          allOf:
            - $ref: '#/components/schemas/Zoo1_Zoo2_Zoo3_Zoo4'
        level3StringProp:
          type: string
      additionalProperties: false
    Zoo1_Zoo2_Zoo3_Zoo4:
      type: object
      properties:
        level4StringProp:
          type: string
      additionalProperties: false
```

### Actual behavior

But generates:

```
    Zoo1:
      type: object
      properties:
        level1:
          allOf:
            - $ref: '#/components/schemas/Zoo1_Zoo2'
        level1StringProp:
          type: string
      additionalProperties: false
    Zoo1_Zoo2:
      type: object
      properties:
        level2:
          allOf:
            - $ref: '#/components/schemas/Zoo1_Zoo2_Zoo3'
        level2StringProp:
          type: string
      additionalProperties: false
    Zoo1_Zoo2_Zoo3:
      type: object
      properties:
        level3:
          allOf:
            - $ref: '#/components/schemas/Zoo1_Zoo2_Zoo3_Zoo4'
          **nullable: true**
        level3StringProp:
          type: string
          **nullable: true**
      additionalProperties: false
    Zoo1_Zoo2_Zoo3_Zoo4:
      type: object
      properties:
        level4StringProp:
          **type: string
          nullable: true**
      additionalProperties: false
```

### Steps to reproduce

As described.

### Exception(s) (if any)

_No response_

### Swashbuckle.AspNetCore version

6.7.1

### .NET Version

8.0.202

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by VladimirTyrin**
# Pull Request

## The issue or feature being addressed

Fixes #3040

## Details on the issue fix or feature implementation

We have to address the case when model type is nested-within-nested. In this case for nullable context analysis we have to traverse the whole declaring type chain

In issue example NullableContextAttribute is on the outer class
Sharplab example: https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UkALIgLIAUAlJtrgL6x0ywKIBOApgMYD2LAJogC0uXCKSEiAdOLCIAMmwBubADYQANMggAGOYpUQAygBcWASwB2AcwAKLLgAdysLDFx5WnHv2ljhYKcJI8krKYBog2rohYMZmVrYOTq64Lm5uzOzcfIKBpBE6wSrwsRY2do4A3NQ4DDRAA

### CODE REVIEW

File: src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs [hunk 1]
```diff
@@ -136,7 +136,7 @@ private static object GetNullableAttribute(this MemberInfo memberInfo)
         private static bool GetNullableFallbackValue(this MemberInfo memberInfo)
         {
             var declaringTypes = memberInfo.DeclaringType.IsNested
-                ? new Type[] { memberInfo.DeclaringType, memberInfo.DeclaringType.DeclaringType }
+                ? GetDeclaringTypeChain(memberInfo)
                 : new Type[] { memberInfo.DeclaringType };
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs:140]: If we changed this to a `List<Type>` then we can avoid the `ToList()` in `GetDeclaringTypeChain()` and just return the list directly.

**Comment by patrikwlund** [comment]
Great fix! I think we see this in our swagger files as well.

I created a sister PR here #3046, that adds some NET6+ specifics on top of this.

File: src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs (hunk 1 above)
Comment (VladimirTyrin) [reply src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs]: Indeed, fixed

**Review by martincostello — APPROVED** [review]
