### PR TITLE
Fix RequestBodyFilterAnnotation and MultipleFromForm for MinimalApi 

### LINKED ISSUE #2662: SwaggerRequestBodyAttribute Description have no effect in Minimal Api
**Minimal API**

I'm using Swashbuckle.AspNetCore 6.5.0 with Swashbuckle.AspNetCore.Annotations 6.5.0 and have added a SwaggerRequestBodyAttribute to a response class thus:

```c#
app.MapPost("/todos", ([FromBody, SwaggerRequestBody("Todo object to be created", Required = true)] Todo todo) =>
    {
        todos.Add(todo with { Id = Guid.NewGuid() });
        return TypedResults.Ok(todo);
    })
    .WithOpenApi(operation => new(operation)
    {
        Summary = "Create a todo",
        OperationId = "createTodo",
        Tags = new List<OpenApiTag> { new() { Name = "Todos" } },
        //Parameters = new List<OpenApiParameter>
        //{
        //    new OpenApiParameter{ Description ="Todo object to be created" }
        //}
    });
```

The project docs say I can use this to "to enrich the corresponding Schema metadata that's generated by Swashbuckle", but the generated swagger.json doesn't contain "MyTitle" or "MyDescription" at all, only:

```json
"post": {
    "tags": [
      "Todos"
    ],
    "summary": "Create a todo",
    "operationId": "createTodo",
    "requestBody": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/Todo"
          }
        }
      },
      "required": true
    },
    "responses": {
      "200": {
        "description": "OK",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Todo"
            }
          }
        }
      }
    }
  }
```

My configurations

```c#
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo { Title = "ChatGPT Plugin", Version = "v1" });
    options.DocInclusionPredicate((docName, apiDesc) => true);
    options.EnableAnnotations();
});
```

### PR DESCRIPTION
**Pull request by jgarciadelanoceda**
Fixes #2662. Very similar to #2962 PR. When the RequestBody had a SwaggerRequestBody attribute the attribute was not applying and it provoked an exception

### CODE REVIEW

**Review by martincostello — COMMENTED** [review]
Could you add a test that shows the description in the attribute is rendered in the generated document please?

The test change here only checks it doesn't cause generation to fail.

**Comment by jgarciadelanoceda** [comment]
It's tested in the test Apply_EnrichesRequestBodyMetadata_IfControllerParameterDecoratedWithSwaggerRequestBodyAttribute of the file AnnotationsRequestBodyFilterTests

**Comment by martincostello** [comment]
I feel we're still missing _something_ in our coverage here, as if we were validating the generated content for a Minimal API using this we would have found this bug before now.

**Comment by jgarciadelanoceda** [comment]
Yeah.. I do agree, altough there is no test for any MinimalApi (Apart from the IntegrationTests). I do not know how to fit this missing tests in the library(You cannot do a MapGet if there is no app. Could we create an issue to test the different apis using MinimalApi

**Comment by martincostello** [comment]
A verification test from the websites should fit this sort of niche.

If we had some in this area already, your addition would have caused a test to fail as the description would have changed, even if the original bug wasn't there.

That suggests to me adding such a test would give us the coverage that the document is what we expect and draw attention to future changes to ensure they are intentional.

**Comment by jgarciadelanoceda** [comment]
Ok, I will add Verify test to the webSites and try to fit the current MinimalApi issues I found over Swashbuckle.

**Comment by jgarciadelanoceda** [comment]
This last commit also fixes #2912.
Added test for the diferent MinimalApi method documentation

File: src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs [hunk 1]
```diff
@@ -420,14 +420,31 @@ private OpenApiOperation GenerateOpenApiOperationFromMetadata(ApiDescription api
             {
                 foreach (var content in requestContentTypes)
                 {
-                    var requestParameter = apiDescription.ParameterDescriptions.SingleOrDefault(desc => desc.IsFromBody() || desc.IsFromForm());
-                    if (requestParameter is not null)
+                    var requestParameters = apiDescription.ParameterDescriptions.Where(desc => desc.IsFromBody() || desc.IsFromForm());
+                    if (requestParameters is not null)
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs:424]: `Where()` will never return `null`.

File: test/WebSites/WebApi/Program.cs [hunk 2]
```diff
@@ -1,60 +1,43 @@
...
+    c.IncludeXmlComments(Assembly.GetExecutingAssembly());
     c.SwaggerDoc("v1", new() { Title = "WebApi", Version = "v1" });
 });
-
 var app = builder.Build();
-
 app.UseSwagger();
 app.UseSwaggerUI();
 
+
```
Comment (martincostello) [inline test/WebSites/WebApi/Program.cs:22]:
```suggestion
```

File: test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+            group.MapPost("/api/people-minimalapi", ([FromForm] Person person, [FromForm] Address address) =>
+            {
+                TypedResults.NoContent();
+            })
+            .WithOpenApi()
+            .DisableAntiforgery();
+
+
+
+            //group.MapGet("DateTimeKind", (DateTimeKind d) => d);
```
Comment (martincostello) [inline test/WebSites/WebApi/EndPoints/OpenApiEndpoints.cs:45]:
```suggestion
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs [hunk 4]
```diff
@@ -421,8 +421,9 @@ private OpenApiOperation GenerateOpenApiOperationFromMetadata(ApiDescription api
                 foreach (var content in requestContentTypes)
                 {
                     var requestParameters = apiDescription.ParameterDescriptions.Where(desc => desc.IsFromBody() || desc.IsFromForm());
-                    if (requestParameters is not null)
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs]: This method is inefficient the way it's using LINQ.

First there's a check for "is there at least one", then there's a check for "is there exactly one" that is discarded, then they're counted, then there's either a `ToList()` if there isn't exactly one or `First()` is called three times to get the same value.

This can be refactored to be smarter.

Comment (jgarciadelanoceda) [reply src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs]: Done, I am not sure if I can remove the discard (To have the same behaviour as before)

File: src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs [hunk 5]
```diff
@@ -421,16 +421,18 @@ private OpenApiOperation GenerateOpenApiOperationFromMetadata(ApiDescription api
                 foreach (var content in requestContentTypes)
                 {
                     var requestParameters = apiDescription.ParameterDescriptions.Where(desc => desc.IsFromBody() || desc.IsFromForm());
-                    if (requestParameters.Any())
+                    var countOfParameters = requestParameters.Count();
+                    if (countOfParameters >= 1)
                     {
                         _ = requestParameters.SingleOrDefault(desc => desc.IsFromBody());
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs:427]: What does this achieve given the result is discarded?

Comment (jgarciadelanoceda) [reply src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs:427]: It will throw when there is more than one Body document, as it was doing previously. It does not make sense to have more than 1 Body element

**Comment by jgarciadelanoceda** [comment]
The build server seems to have a file corrupted :(

File: src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs (hunk 5 above)
Comment (martincostello) [reply src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs:427]: Computing it as a side-effect to throw a not-very-helpful exception message doesn't seem to be desirable behaviour to me. If we want to stop this if it occurs, then we should explicitly check for it and then throw a useful exception, rather than a vague "Sequence contains more than one element" exception.

Comment (jgarciadelanoceda) [reply src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs]: Finally I tried several ways to introduce several FromBody (Passing AsParameters and then FromBody or putting FromBody in just one element and a exception is thrown before reaching Swashbucle code (A binding error)

File: src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs [hunk 6]
```diff
@@ -420,14 +420,33 @@ private OpenApiOperation GenerateOpenApiOperationFromMetadata(ApiDescription api
...
+                                AllOf = requestParameters.Select(s =>
+                                    GenerateSchema(
+                                    s.ModelMetadata.ModelType,
+                                    schemaRepository,
+                                    s.PropertyInfo(),
+                                    s.ParameterInfo()))
+                                .ToList()
+                            };
+                        }
+
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs:449]:
```suggestion
```

**Review by martincostello — APPROVED** [review]

**Comment by jgarciadelanoceda** [comment]
@martincostello  I do not know how the release notes are going to be generated (For the version 6.7.0) but the description of [Fix RequestBodyFilterAnnotation for Minimal API) is missing the multiple FromForms part

**Comment by martincostello** [comment]
They're auto-generated by GitHub and then I'll manually edit anything missing/incorrect/
