### PR TITLE
Optional EOL for XmlComments (#2947)

### LINKED ISSUE #2947: [Bug]: Swagger produces different swagger file on Linux
### Describe the bug

We have Verify tests which compares the swagger files and notifies us if something has changed per accident.

Now we have the issue because of  the addition of #2899 that this produces different results, locally (Windows) and on our Azure Pipelines (Linux). The comparison fails!

The easiest fix would be to make this optionally configurable and let the user decide.
This way I could then fixate the newline characters  

Would be a very nice addition.
Thank u!
Greetings
Florian

### Expected behavior

Newline Characters are configureable

### Actual behavior

Newline Characters are defined by Environment.Newline which differs from the Operating System

### Steps to reproduce

_No response_

### Exception(s) (if any)

_No response_

### Swashbuckle.AspNetCore version

6.6.2

### .NET Version

net8.0

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by RainDance74**
# Pull Request

## The issue or feature being addressed

Fixes #2947 

## Details on the issue fix or feature implementation

Before version [6.6.2,](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/21?closed=1) OpenAPI file generation was identical for Linux and Windows, which allowed to correctly process files from different OS (including comparing them on CI), after the version, the carets in the text began to differ. 
### Example of how it was
{
      “name": ‘SomeController’,
      “description": “Some description.\r\n\n\<br>\r\n\Some Parameter (para tag)\r\n\”
}
### Example of what became
{
      “name": ‘SomeController’,
      “description": “Some description.\r\n[\r\n]|[\n]\r\n\Some Parameter (para tag)\r\n\”
}

That is, instead of <br> being identical when generated on different OS, different strings started to be generated.
The pool requester replaces the generation based on the EOL of the operating system with the EOL generation previously specified in this file (CLRF).

### CODE REVIEW

**Comment by RainDance74** [comment]
Also, I see the possibility of adding configuration from SwaggerGeneratorOptions (with an additional field PrefferedXmlEol - Enum(CLRF, LF)), but I suppose that in this case it will be necessary to make XmlCommentsTextHelper DI service, with the name for example XmlCommentsTextHumanizer in order to be able to throw the generator options into it.

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs [hunk 1]
```diff
@@ -133,7 +136,7 @@ private static string HumanizeParaTags(this string text)
 
         private static string HumanizeBrTags(this string text)
         {
-            return BrTag().Replace(text, _ => Environment.NewLine);
+            return BrTag().Replace(text, _ => ClrfEndOfLine);
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs:139]: I'm hesitant to much this change (as I said in the linked issue) as people may have already depended on this behaviour and changing it may break them.

It would be better to make this configurable, then people who do care about it can opt-in to the fixed value.

We could then remove that option and have consistent behaviour in a future major version.

Comment (RainDance74) [reply src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs:139]: Sure, then, what about my thought above? To make the helper a DI Service

**Comment by RainDance74** [comment]
Fixed with your suggestions, if there is anything to add or to improve, I will be glad to fix it!

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs [hunk 2]
```diff
@@ -89,7 +91,8 @@ public void Apply(OpenApiRequestBody requestBody, RequestBodyFilterContext conte
             var summaryNode = propertyNode.SelectFirstChild("summary");
             if (summaryNode is not null)
             {
-                summary = XmlCommentsTextHelper.Humanize(summaryNode.InnerXml);
+                var preferredEol = _options?.XmlCommentEndOfLine;
+                summary = XmlCommentsTextHelper.Humanize(summaryNode.InnerXml, preferredEol);
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs:95]:
```suggestion
                summary = XmlCommentsTextHelper.Humanize(summaryNode.InnerXml, _options?.XmlCommentEndOfLine);
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs [hunk 3]
```diff
@@ -147,7 +150,8 @@ private void ApplyPropertyTagsForBody(OpenApiRequestBody requestBody, RequestBod
                 return (null, null);
             }
 
-            var summary = XmlCommentsTextHelper.Humanize(paramNode.InnerXml);
+            var preferredEol = _options?.XmlCommentEndOfLine;
+            var summary = XmlCommentsTextHelper.Humanize(paramNode.InnerXml, preferredEol);
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs:154]:
```suggestion
            var summary = XmlCommentsTextHelper.Humanize(paramNode.InnerXml, _options?.XmlCommentEndOfLine);
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs [hunk 4]
```diff
@@ -9,14 +9,16 @@ namespace Swashbuckle.AspNetCore.SwaggerGen
...
         private readonly IReadOnlyDictionary<string, XPathNavigator> _xmlDocMembers;
+        private readonly SwaggerGeneratorOptions _options;
 
-        public XmlCommentsRequestBodyFilter(XPathDocument xmlDoc) : this(XmlCommentsDocumentHelper.CreateMemberDictionary(xmlDoc))
+        public XmlCommentsRequestBodyFilter(XPathDocument xmlDoc) : this(XmlCommentsDocumentHelper.CreateMemberDictionary(xmlDoc), null)
         {
         }
 
-        internal XmlCommentsRequestBodyFilter(IReadOnlyDictionary<string, XPathNavigator> xmlDocMembers)
+        internal XmlCommentsRequestBodyFilter(IReadOnlyDictionary<string, XPathNavigator> xmlDocMembers, SwaggerGeneratorOptions options)
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsRequestBodyFilter.cs:18]:
```suggestion
        [ActivatorUtilitiesConstructor]
        internal XmlCommentsRequestBodyFilter(IReadOnlyDictionary<string, XPathNavigator> xmlDocMembers, SwaggerGeneratorOptions options)
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs [hunk 5]
```diff
@@ -8,14 +8,16 @@ namespace Swashbuckle.AspNetCore.SwaggerGen
...
         private readonly IReadOnlyDictionary<string, XPathNavigator> _xmlDocMembers;
+        private readonly SwaggerGeneratorOptions _options;
 
-        public XmlCommentsSchemaFilter(XPathDocument xmlDoc) : this(XmlCommentsDocumentHelper.CreateMemberDictionary(xmlDoc))
+        public XmlCommentsSchemaFilter(XPathDocument xmlDoc) : this(XmlCommentsDocumentHelper.CreateMemberDictionary(xmlDoc), null)
         {
         }
 
-        internal XmlCommentsSchemaFilter(IReadOnlyDictionary<string, XPathNavigator> xmlDocMembers)
+        internal XmlCommentsSchemaFilter(IReadOnlyDictionary<string, XPathNavigator> xmlDocMembers, SwaggerGeneratorOptions options)
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs:17]:
```suggestion
        [ActivatorUtilitiesConstructor]
        internal XmlCommentsSchemaFilter(IReadOnlyDictionary<string, XPathNavigator> xmlDocMembers, SwaggerGeneratorOptions options)
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs [hunk 6]
```diff
@@ -56,7 +59,10 @@ private void ApplyMemberTags(OpenApiSchema schema, SchemaFilterContext context)
                 {
                     var summaryNode = recordDefaultConstructorProperty.Value;
                     if (summaryNode != null)
-                        schema.Description = XmlCommentsTextHelper.Humanize(summaryNode);
+                    {
+                        var preferredEol = _options?.XmlCommentEndOfLine;
+                        schema.Description = XmlCommentsTextHelper.Humanize(summaryNode, preferredEol);
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs:64]:
```suggestion
                        schema.Description = XmlCommentsTextHelper.Humanize(summaryNode, _options?.XmlCommentEndOfLine);
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs [hunk 7]
```diff
@@ -70,7 +76,10 @@ private void ApplyMemberTags(OpenApiSchema schema, SchemaFilterContext context)
             {
                 var summaryNode = fieldOrPropertyNode.SelectFirstChild("summary");
                 if (summaryNode != null)
-                    schema.Description = XmlCommentsTextHelper.Humanize(summaryNode.InnerXml);
+                {
+                    var preferredEol = _options?.XmlCommentEndOfLine;
+                    schema.Description = XmlCommentsTextHelper.Humanize(summaryNode.InnerXml, preferredEol);
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs:81]:
```suggestion
                    schema.Description = XmlCommentsTextHelper.Humanize(summaryNode.InnerXml, _options?.XmlCommentEndOfLine);
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs [hunk 8]
```diff
@@ -38,7 +40,8 @@ private void ApplyTypeTags(OpenApiSchema schema, Type type)
 
             if (typeSummaryNode != null)
             {
-                schema.Description = XmlCommentsTextHelper.Humanize(typeSummaryNode.InnerXml);
+                var preferredEol = _options?.XmlCommentEndOfLine;
+                schema.Description = XmlCommentsTextHelper.Humanize(typeSummaryNode.InnerXml, preferredEol);
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs:44]:
```suggestion
                schema.Description = XmlCommentsTextHelper.Humanize(typeSummaryNode.InnerXml, _options?.XmlCommentEndOfLine);
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs [hunk 9]
```diff
@@ -131,9 +139,9 @@ private static string HumanizeParaTags(this string text)
             });
         }
 
-        private static string HumanizeBrTags(this string text)
+        private static string HumanizeBrTags(this string text, string xmlCommentEndOfLine)
         {
-            return BrTag().Replace(text, _ => Environment.NewLine);
+            return BrTag().Replace(text, _ => xmlCommentEndOfLine);
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs:144]:
```suggestion
            return BrTag().Replace(text, _ => xmlCommentEndOfLine ?? Environment.NewLine);
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs [hunk 10]
```diff
@@ -46,7 +54,7 @@ private static string NormalizeIndentation(this string text)
 
             // remove leading empty lines, but not all leading padding
             // remove all trailing whitespace, regardless
-            return string.Join("\r\n", lines.SkipWhile(x => string.IsNullOrWhiteSpace(x))).TrimEnd();
+            return string.Join(xmlCommentEndOfLine, lines.SkipWhile(x => string.IsNullOrWhiteSpace(x))).TrimEnd();
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs:57]:
```suggestion
            return string.Join(xmlCommentEndOfLine ?? "\r\n", lines.SkipWhile(x => string.IsNullOrWhiteSpace(x))).TrimEnd();
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs [hunk 11]
```diff
@@ -9,24 +9,32 @@ namespace Swashbuckle.AspNetCore.SwaggerGen
...
+        }
+
+        public static string Humanize(string text, string xmlCommentEndOfLine)
         {
             if (text == null)
                 throw new ArgumentNullException(nameof(text));
 
+            // Using as a default behavior
+            xmlCommentEndOfLine ??= Environment.NewLine;
+
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs:23]: This is a behavioural change - one is currently hardcoded to `"\r\n"` and needs to stay that way, not change to `Environment.NewLine`.

```suggestion
```

**Review by martincostello — APPROVED** [review]
Thanks for your contribution!
