### PR TITLE
Use DeepObject parameter style for dictionary

### LINKED ISSUE #2034: [FromQuery (Name=)] Parameter of type Dictionary does not produce Swagger UI that binds to it
This issue is something that I became aware of due to a bug report in the openapi codegen (https://github.com/OpenAPITools/openapi-generator/issues/8798).

The OpenAPI spec for a method which contains a FromQuery parameter of type dictionary with its name property set produces an openapi spec where the calls produced do not actually bind to the parameter.

Example:

```
  [HttpGet]
        [Route("/v1/getLists/")]
        [ValidateModelState]
        [SwaggerOperation("GetLists")]
        [SwaggerResponse(statusCode: 200, description: "Wow")]
        public virtual IActionResult GetLists([FromQuery (Name = "amount")][Required()]int amount, [FromQuery (Name = "which")][Required()]Dictionary<string, string> which)
        { 
```

produces a spec of:

```
 "/v1/getLists": {
      "get": {
        "tags": [
          "CustomersApi"
        ],
        "summary": "",
        "parameters": [
          {
            "name": "amount",
            "in": "query",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "which",
            "in": "query",
            "description": "",
            "required": true,
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Wow"
          }
        }
      }
```

Which in SwaggerUI produces queries of the form:
```
http://localhost:8080/v1/getLists?amount=100&additionalProp1=string&additionalProp2=string&additionalProp3=string
```

Which do NOT map to the FromQuery parameter.

If you add
```
"style" : "deepObject"
```

to the parameter SwaggerUI produces queries that do bind of the form:
```
http://localhost:8080/v1/getLists/?amount=100&which[additionalProp1]=string&which[additionalProp2]=string&which[additionalProp3]=string
```

### PR DESCRIPTION
**Pull request by EvgeniyZ**
## The issue or feature being addressed

Resolves #2034.

### CODE REVIEW

File: src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs [hunk 1]
```diff
@@ -367,15 +367,13 @@ private OpenApiSchema CreateDictionarySchema(DataContract dataContract, SchemaRe
                     AdditionalPropertiesAllowed = false
                 };
             }
-            else
+
+            return new OpenApiSchema
```
Comment (EvgeniyZ) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs:371]: no logical changes, refactoring

File: src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs [hunk 2]
```diff
@@ -602,10 +602,14 @@ private OpenApiParameter GenerateParameterWithoutFilter(
...
                 Required = isRequired,
                 Schema = schema,
-                Description = description
+                Description = description,
+                Style = GetParameterStyle(type, apiParameter.Source)
             };
         }
 
+        private static ParameterStyle? GetParameterStyle(Type type, BindingSource source) =>
+            source == BindingSource.Query && type == typeof(Dictionary<string, string>) ? ParameterStyle.DeepObject : null;
```
Comment (EvgeniyZ) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs:611]: I am not sure about the implementation, I decided to keep strict type equality to `Dictionary<string, string>`, but maybe in swagger makes sense to make any [FromQuery] IDictionary type (or type that implements IDictionary) to have "style": "deepObject"

Comment (martincostello) [reply src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs:611]: Other types we could consider checking instead could be:

- `IDictionary<string, string>`
- `IReadOnlyDictionary<string, string>`
- `IEnumerable<KeyValuePair<string, string>>`

Comment (EvgeniyZ) [reply src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs]: applied suggestion

File: src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs [hunk 3]
```diff
@@ -602,10 +602,28 @@ private OpenApiParameter GenerateParameterWithoutFilter(
...
+            bool IsKeyValueStringsPairCollection(Type t)
+            {
+                if (!t.IsGenericType)
+                {
+                    return false;
+                }
+
+                return typeof(IDictionary<string, string>).IsAssignableFrom(t) ||
+                       typeof(IReadOnlyDictionary<string, string>).IsAssignableFrom(t) ||
+                       typeof(IEnumerable<KeyValuePair<string, string>>).IsAssignableFrom(t);
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs:623]: The first two both inherit from the third, so either we only want just the first two or it's just the third one.

Comment (EvgeniyZ) [reply src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs]: thanks, I think it's OK to support `IEnumerable<KeyValuePair<string, string>>`
