### PR TITLE
Resolves #2717

### LINKED ISSUE #2717: XmlCommentsDocumentFilter incorrect comment controller tags names.
In Swashbuckle.AspNetCore.SwaggerGen v6.5.0

There appears to be a bug in [XmlCommentsDocumentFilter.cs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs#L28)

Simple reproduction steps are to create an [ApiController] and set a [ControllerName(...)] attribute on it which overrides the controller's name to something else, example:

```csharp
// simple setup with including xml comments
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
    c.IncludeXmlComments(..., includeControllerXmlComments: true);
});

/// <summary>
/// My test controller to prove bugs
/// </summary>
[ApiController]
[Route("api/test")]
[ControllerName("Test")]
public class MyTestController : ControllerBase
{
    /// <summary>
    /// Returns something else
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public IActionResult Index()
    {
        return Ok(new { Something = "Hello", Else = "World" });
    }
}
```

The default SwaggerGeneratorOptions.TagsSelector uses the RouteValues["controller"] as the tag it puts on actions, but the XmlCommentsDocumentFilter.cs will create the tag using ControllerName which is the original/raw name (minus the Controller suffix if it exists).

This leads to ReDoc and Swagger UI to show an extra section with the raw controller name and the comment, and a separate section with the action actions.

Expected behavior would be that controller comments properly show up under the "Test" section.

image

image

### PR DESCRIPTION
**Pull request by MerickOWA**
This resolves #2717 by switching how comments are tagged using the SwaggerGeneratorOptions

### CODE REVIEW

**Comment by martincostello** [comment]
Thanks for contributing - if you'd like to continue with this pull request, please rebase against the default branch to pick up our new CI.

**Comment by MerickOWA** [comment]
@martincostello I've re-commited the code against the latest branch.

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs [hunk 1]
```diff
@@ -12,21 +12,22 @@ public class XmlCommentsDocumentFilter : IDocumentFilter
         private const string MemberXPath = "/doc/members/member[@name='{0}']";
         private const string SummaryTag = "summary";
 
+        private readonly SwaggerGeneratorOptions _options;
         private readonly XPathNavigator _xmlNavigator;
 
-        public XmlCommentsDocumentFilter(XPathDocument xmlDoc)
+        public XmlCommentsDocumentFilter(SwaggerGeneratorOptions options, XPathDocument xmlDoc)
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs:18]: As this type is public, this is a binary-breaking change that we couldn't merge until a major version (e.g. 7.0.0).

Is there a way you can make this compatible when `SwaggerGeneratorOptions` is optional so we can add a constructor overload instead?

```csharp
public XmlCommentsDocumentFilter(XPathDocument xmlDoc)
    : (xmlDoc, null)
{
}

public XmlCommentsDocumentFilter(XPathDocument xmlDoc, SwaggerGeneratorOptions options)
{
    // Set properties, allowing options to be null
}
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs [hunk 2]
```diff
@@ -12,21 +12,22 @@ public class XmlCommentsDocumentFilter : IDocumentFilter
...
         {
             // Collect (unique) controller names and types in a dictionary
             var controllerNamesAndTypes = context.ApiDescriptions
-                .Select(apiDesc => apiDesc.ActionDescriptor as ControllerActionDescriptor)
-                .Where(actionDesc => actionDesc != null)
-                .GroupBy(actionDesc => actionDesc.ControllerName)
-                .Select(group => new KeyValuePair<string, Type>(group.Key, group.First().ControllerTypeInfo.AsType()));
+                .Where(apiDesc => apiDesc.ActionDescriptor is ControllerActionDescriptor)
+                .GroupBy(apiDesc => _options.TagsSelector(apiDesc).First())
+                .Select(group => new KeyValuePair<string, Type>(group.Key, ((ControllerActionDescriptor)group.First().ActionDescriptor).ControllerTypeInfo.AsType()));
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs:30]: I think it's better with the `as` and the null check, rather than the `is` and then a cast.

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs [hunk 3]
```diff
@@ -23,32 +25,72 @@ public void Apply_SetsTagDescription_FromControllerSummaryTags()
...
 
             var tag = Assert.Single(document.Tags);
             Assert.Equal("Summary for FakeControllerWithXmlComments", tag.Description);
         }
 
-        private static XmlCommentsDocumentFilter Subject()
+        [Fact]
+        public void Uses_Proper_Tag_Name()
+        {
+            var options = new SwaggerGeneratorOptions();
```
Comment (martincostello) [inline test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs:54]: Could we add a test with a custom tag selector as well?

Comment (MerickOWA) [reply test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs:60]: Done

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs (hunk 2 above)
Comment (MerickOWA) [reply src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs]: Ok, I changed it to accomplish that by selecting an anonymous type to capture both the original apiDesc as well actionDesc as well.

File: src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs [hunk 4]
```diff
@@ -436,7 +436,7 @@ public static void SupportNonNullableReferenceTypes(this SwaggerGenOptions swagg
             swaggerGenOptions.SchemaFilter<XmlCommentsSchemaFilter>(xmlDoc);
 
             if (includeControllerXmlComments)
-                swaggerGenOptions.DocumentFilter<XmlCommentsDocumentFilter>(xmlDoc);
+                swaggerGenOptions.DocumentFilter<XmlCommentsDocumentFilter>(swaggerGenOptions.SwaggerGeneratorOptions, xmlDoc);
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs:439]: Looks like these parameters are the wrong way around - it concerns me that none of the tests have failed because of that 😓

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs [hunk 5]
```diff
@@ -13,20 +13,27 @@ public class XmlCommentsDocumentFilter : IDocumentFilter
...
             // Collect (unique) controller names and types in a dictionary
             var controllerNamesAndTypes = context.ApiDescriptions
-                .Select(apiDesc => apiDesc.ActionDescriptor as ControllerActionDescriptor)
-                .Where(actionDesc => actionDesc != null)
-                .GroupBy(actionDesc => actionDesc.ControllerName)
-                .Select(group => new KeyValuePair<string, Type>(group.Key, group.First().ControllerTypeInfo.AsType()));
+                .Select(apiDesc => new { apiDesc = apiDesc, actionDesc = apiDesc.ActionDescriptor as ControllerActionDescriptor })
+                .Where(x => x.actionDesc != null)
+                .GroupBy(x => _options?.TagsSelector(x.apiDesc).FirstOrDefault() ?? x.actionDesc.ControllerName)
+                .Select(group => new KeyValuePair<string, Type>(group.Key, group.First().actionDesc.ControllerTypeInfo.AsType()));
```
Comment (martincostello) [inline src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs:36]: Just a minor style nit:

```suggestion
                .Select(apiDesc => new { ApiDesc = apiDesc, ActionDesc = apiDesc.ActionDescriptor as ControllerActionDescriptor })
                .Where(x => x.ActionDesc != null)
                .GroupBy(x => _options?.TagsSelector(x.ApiDesc).FirstOrDefault() ?? x.ActionDesc.ControllerName)
                .Select(group => new KeyValuePair<string, Type>(group.Key, group.First().ActionDesc.ControllerTypeInfo.AsType()));
```

File: src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs (hunk 4 above)
Comment (MerickOWA) [reply src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs]: It appears that it actually worked with the arguments in the wrong order, but I went ahead and fixed it.

I also added a unit test to prove that it works, maybe it should be moved somewhere else, but I couldn't find a similar unit test class.

File: src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs (hunk 5 above)
Comment (MerickOWA) [reply src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs]: Fixed

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs [hunk 6]
```diff
@@ -51,5 +53,114 @@ private static XmlCommentsDocumentFilter Subject()
...
+                c.IncludeXmlComments(
+                    $"{typeof(FakeControllerWithXmlComments).Assembly.GetName().Name}.xml",
+                    includeControllerXmlComments: true);
+            });
+
+            var provider = services.BuildServiceProvider();
+            var options = provider.GetService<Microsoft.Extensions.Options.IOptions<SwaggerGeneratorOptions>>().Value;
+
+            Assert.NotNull(options);
+            Assert.Contains(options.DocumentFilters, x => x is XmlCommentsDocumentFilter filter);
```
Comment (martincostello) [inline test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs:153]:
```suggestion
            Assert.Contains(options.DocumentFilters, x => x is XmlCommentsDocumentFilter);
```

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs [hunk 7]
```diff
@@ -51,5 +53,114 @@ private static XmlCommentsDocumentFilter Subject()
...
+        }
+
+        class DummyHostEnvironment : Microsoft.AspNetCore.Hosting.IWebHostEnvironment
```
Comment (martincostello) [inline test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs:156]:
```suggestion
        private sealed class DummyHostEnvironment : IWebHostEnvironment
```

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs [hunk 8]
```diff
@@ -51,5 +53,114 @@ private static XmlCommentsDocumentFilter Subject()
...
+            {
+                return new XmlCommentsDocumentFilter(new XPathDocument(xmlComments), options);
+            }
+        }
+
+        [Fact]
+        public void Ensure_IncludeXmlComments_Adds_Filter_To_Options()
+        {
+            var services = new ServiceCollection();
+            services.AddSingleton<Microsoft.AspNetCore.Hosting.IWebHostEnvironment, DummyHostEnvironment>();
```
Comment (martincostello) [inline test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs:141]: As it's used in two places, let's add the `using` at the top of the file.

```suggestion
            services.AddSingleton<IWebHostEnvironment, DummyHostEnvironment>();
```

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs [hunk 9]
```diff
@@ -51,5 +53,114 @@ private static XmlCommentsDocumentFilter Subject()
...
+            Assert.NotNull(options);
+            Assert.Contains(options.DocumentFilters, x => x is XmlCommentsDocumentFilter filter);
+        }
+
+        class DummyHostEnvironment : Microsoft.AspNetCore.Hosting.IWebHostEnvironment
+        {
+            public string WebRootPath { get; set; }
+            public Microsoft.Extensions.FileProviders.IFileProvider WebRootFileProvider { get; set; }
+            public string ApplicationName { get; set; }
+            public Microsoft.Extensions.FileProviders.IFileProvider ContentRootFileProvider { get; set; }
```
Comment (martincostello) [inline test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs:161]: Same here:
```suggestion
            public IFileProvider WebRootFileProvider { get; set; }
            public string ApplicationName { get; set; }
            public IFileProvider ContentRootFileProvider { get; set; }
```

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs [hunk 10]
```diff
@@ -51,5 +53,114 @@ private static XmlCommentsDocumentFilter Subject()
...
+            var services = new ServiceCollection();
+            services.AddSingleton<Microsoft.AspNetCore.Hosting.IWebHostEnvironment, DummyHostEnvironment>();
+            services.AddSwaggerGen(c =>
+            {
+                c.IncludeXmlComments(
+                    $"{typeof(FakeControllerWithXmlComments).Assembly.GetName().Name}.xml",
+                    includeControllerXmlComments: true);
+            });
+
+            var provider = services.BuildServiceProvider();
```
Comment (martincostello) [inline test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs:149]:
```suggestion
            using var provider = services.BuildServiceProvider();
```

**Review by martincostello — COMMENTED** [review]
Just a few minor comments - thanks for adding the test that double-checks the DI registration.

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs (hunk 6 above)
Comment (MerickOWA) [reply test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs]: done

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs (hunk 7 above)
Comment (MerickOWA) [reply test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs]: done

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs (hunk 8 above)
Comment (MerickOWA) [reply test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs]: done

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs (hunk 9 above)
Comment (MerickOWA) [reply test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs]: done

File: test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs (hunk 10 above)
Comment (MerickOWA) [reply test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/XmlCommentsDocumentFilterTests.cs]: done
